version: '3.8'
services:
 postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: photoscout-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

 backend:
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - postgres

 frontend:
    build: ./client
    ports:
      - 3001:3000
    depends_on:
      - backend

volumes:
 postgres-data: