version: '3.8'
services:
 backend:
    image: izayaaaaa/backend:latest
    ports:
      - "3333:3333"
    depends_on:
      - db
 db:
    image: izayaaaaa/postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"