name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install_and_start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Start server
        run: |
          cd server
          npm start &

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Start client
        run: |
          cd client
          npm start &
