name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build PostgreSQL
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/postgres .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest

      - name: Build backend
        run: |
          cd server
          npm install
          npm run build
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  run_e2e_tests:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Run Docker images
        run: |
          docker run -d -p 5432:5432 ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker run -d -p 3333:3333 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Wait for backend to be ready
        run: |
          # Replace this with a command that waits for your backend to be ready
          # For example, using curl to check a health check endpoint
          sleep 15 # Wait for 15 seconds to give the backend time to start

      - name: Run E2E tests
        run: |
          cd server
          npm run test:e2e:cicd
