name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build PostgreSQL
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/postgres .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest

      - name: Build backend
        run: |
          cd server
          npm install
          npm run build
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  run_e2e_tests:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker images
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker run -d -p 3333:3333 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest
          docker run -d -p 5432:5432 ${{ secrets.DOCKERHUB_USERNAME }}/postgres:latest

      - name: Run e2e tests
        run: |
          cd server
          npm run test:e2e:cicd
